name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Be sure you check-out the repo first. Deta CLI needs access to the files
      - uses: HarshKapadia2/deta-deploy@v1.0.2
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'core' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: 'SocialIcebreakerGame' #Optional: Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project-dir: 'app' #Optional: directory to be deployed on Deta. Default is the root "." 
